version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: quiniela_postgres
    environment:
      POSTGRES_DB: quiniela_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer para administrar la DB (opcional)
  adminer:
    image: adminer
    container_name: quiniela_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: